# Generated by Django 5.0.7 on 2024-08-09 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pokemon', '0002_alter_pokemon_original_trainer_alter_pokemon_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slot_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot1', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot2', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot3', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot4', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot5', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slot_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot6', to='pokemon.pokemon'),
        ),
    ]
