# Generated by Django 5.0.7 on 2024-09-26 19:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_slot_1_profile_slot_2_profile_slot_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bag',
            field=models.JSONField(default=accounts.models.default_bag),
        ),
        migrations.AddField(
            model_name='profile',
            name='map_progress',
            field=models.JSONField(default=accounts.models.default_map),
        ),
    ]
