# Generated by Django 5.0.7 on 2024-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bag_profile_map_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_map',
            field=models.TextField(default='oak_village', max_length=20),
        ),
    ]
