# Generated by Django 5.0.7 on 2024-09-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_current_map'),
        ('battle', '0002_battle_output_log_alter_battle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.battle'),
        ),
    ]
