# Generated by Django 5.0.7 on 2024-10-22 18:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_wild_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.JSONField(default=accounts.models.default_badges),
        ),
        migrations.AddField(
            model_name='profile',
            name='pokedex_progress',
            field=models.JSONField(default=accounts.models.default_pokedex),
        ),
    ]
