# Generated by Django 5.0.7 on 2024-10-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_badges_profile_pokedex_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trainer_points',
            field=models.IntegerField(default=0),
        ),
    ]
