# Generated by Django 5.0.7 on 2024-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_trainer_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Novice Trainer', max_length=50),
        ),
    ]
