# Generated by Django 5.0.7 on 2024-10-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badges',
        ),
    ]
