# Generated by Django 5.0.7 on 2024-10-23 19:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.JSONField(default=accounts.models.default_badges),
        ),
    ]
