# Generated by Django 5.0.7 on 2024-10-25 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_bag_profile_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='money',
        ),
    ]
