# Generated by Django 5.0.7 on 2024-10-25 01:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_bag_remove_profile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bag',
            field=models.JSONField(default=accounts.models.default_bag),
        ),
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=100000),
        ),
    ]
