# Generated by Django 5.0.7 on 2024-12-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wild_opponent',
        ),
        migrations.AddField(
            model_name='profile',
            name='wild_opponent',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
