# Generated by Django 5.0.7 on 2024-12-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profile_wild_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_pos',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
