# Generated by Django 5.0.7 on 2024-12-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_last_update_profile_trainers_beat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_update',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
