# Generated by Django 5.0.7 on 2025-01-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('items', models.JSONField(blank=True, default=None, null=True)),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='accounts.profile')),
                ('sender', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='accounts.profile')),
            ],
        ),
    ]
