# Generated by Django 5.0.7 on 2025-01-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_messages_recipient_alter_messages_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='items',
            new_name='gift_items',
        ),
    ]
