# Generated by Django 5.0.7 on 2025-01-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_items_messages_gift_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inbox_flag',
            field=models.BooleanField(default=False),
        ),
    ]
