# Generated by Django 5.0.7 on 2025-01-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_profile_inbox_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender_spr',
            field=models.CharField(default='01', max_length=20),
            preserve_default=False,
        ),
    ]
