# Generated by Django 5.0.7 on 2025-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_messages_sender_spr'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_city',
            field=models.TextField(default='oak_village', max_length=20),
        ),
    ]
