# Generated by Django 5.0.7 on 2025-02-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_profile_last_city'),
        ('battle', '0008_gauntlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_gauntlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.gauntlet'),
        ),
    ]
