import random
# Mappings of sprite names to display name and gender
# Can be used to generate random names
# If sprite is not listed, it is assumed it can be capitalized to get the trainer name
mapping = {
    "ace_trainer_f": ("Ace Trainer", "f"),
    "ace_trainer_m": ("Ace Trainer", "m"),
    "artist": ("Artist", "mo"),
    "backpacker_f": ("Backpacker", "f"),
    "backpacker_m": ("Backpacker", "m"),
    "baker": ("Baker", "f"),
    "battlegirl": ("Battle Girl", "f"),
    "beauty": ("Beauty", "f"),
    "blackbelt": ("Black Belt", "m"),
    "boarder": ("Boarder", "m"),
    "bounty_hunter_f": ("Bounty Hunter", "f"),
    "bounty_hunter_m": ("Bounty Hunter", "m"),
    "breeder_f": ("Pokémon Breeder", "f"),
    "breeder_m": ("Pokémon Breeder", "m"),
    "bug_catcher": ("Bug Catcher", "my"),
    "clerk_b": ("Boss", "mo"),
    "clerk_f": ("Clerk", "f"),
    "clerk_m": ("Clerk", "m"),
    "cool_trainer_f": ("Cool Trainer", "f"),
    "cool_trainer_m": ("Cool Trainer", "m"),
    "challenger_f": ("Challenger", "fo"),
    "challenger_m": ("Challenger", "mo"),
    "cyclist_f": ("Cyclist", "f"),
    "cyclist_m": ("Cyclist", "m"),
    "dancer": ("Dancer", "m"),
    "doctor": ("Doctor", "m"),
    "elite_trainer_f": ("Elite Trainer", "f"),
    "elite_trainer_m": ("Elite Trainer", "m"),
    "expert_trainer_f": ("Expert Trainer", "fo"),
    "expert_trainer_m": ("Expert Trainer", "mo"),
    "firebreather": ("Firebreather", "m"),
    "fisher": ("Fisher", "m"),
    "gentleman": ("Gentleman", "mo"),
    "harlequin": ("Harlequin", "m"),
    "hiker": ("Hiker", "m"),
    "hoopster": ("Hoopster", "m"),
    "infielder": ("Infielder", "m"),
    "janitor": ("Janitor", "m"),
    "kimono_girl": ("Kimono Girl", "f"),
    "lady": ("Lady", "f"),
    "lass": ("Lass", "fy"),
    "linebacker": ("Linebacker", "m"),
    "maid": ("Maid", "f"),
    "musician": ("Musician", "m"),
    "nurse": ("Nurse", "f"),
    "nursery_aide": ("Nursery Aide", "f"),
    "parasol_lady": ("Parasol Lady", "f"),
    "picnicker_f": ("Picnicker", "fy"),
    "picnicker_m": ("Camper", "my"),
    "pilot": ("Pilot", "m"),
    "plasma_grunt_f": ("Plasma Grunt", "f"),
    "plasma_grunt_m": ("Plasma Grunt", "m"),
    "pokefan_f": ("Pokémaniac", "f"),
    "pokefan_m": ("Pokémaniac", "m"),
    "policeman": ("Policeman", "mo"),
    "preschooler_f": ("Preschooler", "fy"),
    "preschooler_m": ("Preschooler", "my"),
    "pro_trainer_f": ("Pro Trainer", "f"),
    "pro_trainer_m": ("Pro Trainer", "m"),
    "prime_trainer_f": ("Prime Trainer", "f"),
    "prime_trainer_m": ("Prime Trainer", "m"),
    "psychic_f": ("Psychic", "f"),
    "psychic_m": ("Psychic", "m"),
    "ranger_f": ("Ranger", "f"),
    "ranger_m": ("Ranger", "m"),
    "rich_boy": ("Rich Boy", "my"),
    "rocket_grunt_f": ("Rocket Grunt", "f"),
    "rocket_grunt_m": ("Rocket Grunt", "m"),
    "roughneck": ("Cue Ball", "m"),
    "sailor": ("Sailor", "m"),
    "school_kid_f": ("School Kid", "fy"),
    "school_kid_m": ("School Kid", "my"),
    "scientist_f": ("Scientist", "f"),
    "scientist_m": ("Scientist", "m"),
    "skier_f": ("Skier", "f"),
    "skier_m": ("Skier", "m"),
    "smasher": ("Smasher", "f"),
    "socialite": ("Socialite", "fo"),
    "swimmer_f": ("Swimmer", "f"),
    "swimmer_m": ("Swimmer", "m"),
    "veteran_f": ("Veteran", "fo"),
    "veteran_m": ("Veteran", "mo"),
    "waiter": ("Waiter", "m"),
    "waitress": ("Waitress", "f"),
    "worker": ("Worker", "m"),
    "youngster": ("Youngster", "my")
}

names = {
    "m": ['Christopher', 'Matthew', 'Joshua', 'Jacob', 'Nicholas', 'Andrew', 'Daniel', 'Tyler', 'Joseph', 'Brandon', 'David', 'James', 'Ryan', 'John', 'Zachary', 'Justin', 'William', 'Anthony', 'Robert', 'Jonathan', 'Austin', 'Alexander', 'Kyle', 'Kevin', 'Thomas', 'Cody', 'Jordan', 'Eric', 'Benjamin', 'Aaron', 'Christian', 'Samuel', 'Dylan', 'Steven', 'Brian', 'Jose', 'Timothy', 'Nathan', 'Adam', 'Richard', 'Patrick', 'Charles', 'Sean', 'Jason', 'Cameron', 'Jeremy', 'Mark', 'Stephen', 'Jesse', 'Juan'],
    "f": ['Ashley', 'Emily', 'Sarah', 'Samantha', 'Amanda', 'Brittany', 'Elizabeth', 'Taylor', 'Megan', 'Hannah', 'Kayla', 'Lauren', 'Stephanie', 'Rachel', 'Jennifer', 'Nicole', 'Alexis', 'Victoria', 'Amber', 'Alyssa', 'Courtney', 'Rebecca', 'Danielle', 'Jasmine', 'Brianna', 'Katherine', 'Alexandra', 'Madison', 'Morgan', 'Melissa', 'Michelle', 'Kelsey', 'Chelsea', 'Anna', 'Kimberly', 'Tiffany', 'Olivia', 'Mary', 'Christina', 'Allison', 'Abigail', 'Sara', 'Shelby', 'Heather', 'Haley', 'Maria', 'Kaitlyn', 'Laura', 'Erin', 'Andrea'],
    "my": ['Liam', 'Jacob', 'William', 'Mason', 'Ethan', 'Michael', 'Alexander', 'James', 'Elijah', 'Benjamin', 'Daniel', 'Aiden', 'Logan', 'Jayden', 'Matthew', 'Lucas', 'David', 'Jackson', 'Joseph', 'Anthony', 'Samuel', 'Joshua', 'Gabriel', 'Andrew', 'John', 'Christopher', 'Oliver', 'Dylan', 'Carter', 'Isaac', 'Luke', 'Henry', 'Owen', 'Ryan', 'Nathan', 'Wyatt', 'Caleb', 'Sebastian', 'Jack', 'Christian', 'Jonathan', 'Julian', 'Landon', 'Levi', 'Isaiah', 'Hunter', 'Aaron', 'Thomas', 'Charles', 'Eli'],
    "fy": ['Olivia', 'Sophia', 'Isabella', 'Ava', 'Mia', 'Abigail', 'Emily', 'Charlotte', 'Madison', 'Elizabeth', 'Amelia', 'Evelyn', 'Ella', 'Chloe', 'Harper', 'Avery', 'Sofia', 'Grace', 'Addison', 'Victoria', 'Lily', 'Natalie', 'Aubrey', 'Zoey', 'Lillian', 'Hannah', 'Layla', 'Brooklyn', 'Scarlett', 'Zoe', 'Camila', 'Samantha', 'Riley', 'Leah', 'Aria', 'Savannah', 'Audrey', 'Anna', 'Allison', 'Gabriella', 'Hailey', 'Claire', 'Penelope', 'Aaliyah', 'Sarah', 'Nevaeh', 'Kaylee', 'Stella', 'Mila', 'Nora'],
    "mo": ['Michael', 'Robert', 'John', 'David', 'William', 'Richard', 'Thomas', 'Mark', 'Charles', 'Steven', 'Gary', 'Joseph', 'Donald', 'Ronald', 'Kenneth', 'Paul', 'Larry', 'Daniel', 'Stephen', 'Dennis', 'Timothy', 'Edward', 'Jeffrey', 'George', 'Gregory', 'Kevin', 'Douglas', 'Terry', 'Anthony', 'Jerry', 'Bruce', 'Randy', 'Brian', 'Frank', 'Scott', 'Roger', 'Raymond', 'Peter', 'Patrick', 'Keith', 'Lawrence', 'Wayne', 'Danny', 'Alan', 'Gerald', 'Ricky', 'Carl', 'Christopher', 'Dale', 'Walter'],
    "fo": ['Linda', 'Patricia', 'Susan', 'Deborah', 'Barbara', 'Debra', 'Karen', 'Nancy', 'Donna', 'Cynthia', 'Sandra', 'Pamela', 'Sharon', 'Kathleen', 'Carol', 'Diane', 'Brenda', 'Cheryl', 'Janet', 'Elizabeth', 'Kathy', 'Margaret', 'Janice', 'Carolyn', 'Denise', 'Judy', 'Rebecca', 'Joyce', 'Teresa', 'Christine', 'Catherine', 'Shirley', 'Judith', 'Betty', 'Beverly', 'Lisa', 'Laura', 'Theresa', 'Connie', 'Ann', 'Gloria', 'Julie', 'Gail', 'Joan', 'Paula', 'Peggy', 'Cindy', 'Martha', 'Bonnie', 'Jane'],
}

def gen_name(trainer, name=None):
    if trainer in mapping:
        prefix = mapping[trainer][0]
        if name is None:
            name = random.choice(names[mapping[trainer][1]])
        return "{} {}".format(prefix, name)
    return trainer.replace("_", " ").capitalize()