# Generated by Django 5.0.7 on 2024-08-06 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_ability_alter_pokemon_ball_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='caught_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
