# Generated by Django 5.0.7 on 2024-08-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_pokemon_box_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Party',
        ),
    ]
