# Generated by Django 5.0.7 on 2024-08-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_delete_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='bst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='iv_total',
            field=models.IntegerField(default=0),
        ),
    ]
