# Generated by Django 5.0.7 on 2024-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_pokemon_bst_pokemon_iv_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
