# Generated by Django 5.0.7 on 2024-11-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_pokemon_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='status_turns',
            field=models.IntegerField(default=0),
        ),
    ]
