# Generated by Django 5.0.7 on 2024-09-26 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_profile_bag_profile_map_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=15)),
                ('player_1_choice', models.JSONField(blank=True, null=True)),
                ('player_2_choice', models.JSONField(blank=True, null=True)),
                ('current_turn', models.IntegerField(default=1)),
                ('move_history', models.JSONField(blank=True, null=True)),
                ('battle_state', models.JSONField(blank=True, null=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='accounts.profile')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='accounts.profile')),
            ],
        ),
    ]
