# Generated by Django 5.0.7 on 2024-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='output_log',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('live', 'Live Battle'), ('wild', 'Wild Battle'), ('npc', 'Trainer Battle')], max_length=10),
        ),
    ]
