# Generated by Django 5.0.7 on 2024-10-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_battle_output_log_alter_battle_type'),
        ('pokemon', '0007_pokemon_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='npc_opponent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='wild_opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon'),
        ),
    ]
