# Generated by Django 5.0.7 on 2024-10-07 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_battle_npc_opponent_battle_wild_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='battle_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='last_move_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battle',
            name='move_history',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='output_log',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player_1_choice',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player_2_choice',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
