# Generated by Django 5.0.7 on 2024-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_battle_battle_end_battle_battle_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='battle_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
