# Generated by Django 5.0.7 on 2025-01-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_battle_battle_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='background',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
