# Generated by Django 5.0.7 on 2025-02-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_profile_last_city'),
        ('battle', '0007_battle_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gauntlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauntlet_type', models.CharField(choices=[('bounty', 'Bounty'), ('mansion', 'Battle Mansion')], max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('team_mutable', models.BooleanField(default=False)),
                ('can_heal', models.BooleanField(default=False)),
                ('team_state', models.JSONField(blank=True, default=None, null=True)),
                ('gauntlet_state', models.JSONField(blank=True, default=None, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
