# Generated by Django 5.0.7 on 2025-02-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_battle_gauntlet_gauntlet_current_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='save_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='save_team',
            field=models.BooleanField(default=True),
        ),
    ]
