# Generated by Django 5.1.5 on 2025-03-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_battle_save_inventory_battle_save_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='background',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='npc_opponent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
